services:
  mongo:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: latest
    environment:
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: krycfalusijtomas
      MONGO_INITDB_ROOT_PASSWORD: Admin123!
      MONGO_INITDB_DATABASE: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  prisma:
    image: prisma/prisma:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://mongo:27017/mongo

volumes:
  mongo-data:
