import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/app/page.module.css";
import { getDaysFromDatabase } from "./getDays";
import Days from "../components/Days";
import { DayType } from "../types/types";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = async () => {

  const days = await getDaysFromDatabase();
  console.log(days);

  return (
    <>
      <Head>
        <title>Parking slot reservation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Registrace</h1>
        <Days days={days} />
      </main>
    </>
  );
};

export default Home;
