"use client"
// pages/index.tsx
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/app/page.module.css";
import { useEffect, useState } from "react";
import connectToDatabase from "../../lib/mongodb";
import { mongo } from "mongoose";

const inter = Inter({ subsets: ["latin"] });

export type Day = {
  _id: string;
  date: string;
  capacity: number;
  bookings: string[];
};

const Home: React.FC = () => {
  const [days, setDays] = useState<Day[]>([]);
  

  useEffect(() => {
    async function fetchDays() {
      await connectToDatabase();
      
      const response = await connectToDatabase();
      console.log("RESPONSE", response)
      /*
      const data = await response.json();
      console.log("data", data);
      setDays(data);
      */
    }

    fetchDays();
  }, []);

  return (
    <>
      <Head>
        <title>Parking slot reservation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Registrace</h1>
        <ul>
          {days.map((day) => (
            <li key={day._id}>
              {new Date(day.date).toLocaleDateString()} - {day.capacity}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
